name: flutter_bt_test
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter_launcher_icons: ^0.14.2
  flutter_blue_plus: ^1.34.5
  flip_card: ^0.7.0
  cupertino_icons: ^1.0.5
  permission_handler: ^11.3.1
  intl: ^0.20.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "lib/images/SmartIndustryFondo.png" 
  #image_path: "assets/images/app_icon.png"
